### ISSUE TITLE
Broken links in Readme

### ISSUE THREAD

**Issue by kimjj93** [phuse-org/E2E-OS-Guidance#11]
I merged #10 but some links look like they are broken in "Built-with"

Built With
[![Next][Next.js]][Next-url]
[![React][React.js]][React-url]
[![Vue][Vue.js]][Vue-url]
[![Angular][Angular.io]][Angular-url]
[![Svelte][Svelte.dev]][Svelte-url]
[![Laravel][Laravel.com]][Laravel-url]
[![Bootstrap][Bootstrap.com]][Bootstrap-url]
[![JQuery][JQuery.com]][JQuery-url]

@epijim - any thoughts?

**Comment by epijim** [comment]
thanks for flagging that! Was copied over from the README template.

fixed in PR #13
