### ISSUE TITLE
Feedback by Phil (Posit)

### ISSUE THREAD

**Issue by philbowsher** [phuse-org/E2E-OS-Guidance#19]
"well as collaboration on and creation of open-source projects used by data scientists in clinical reporting workflows"
You could include statistical programmer, researcher, scientist etc. PhUSE members consist of many roles etc.

"Open source: the what and why"
Open source is also a step towards insuring "repoducibility"... should be "reproducibility" yea? 

Also, some good info below on that topic: 

https://nuest.staff.ifgi.de/N%C3%BCst-and-Pebesma_2020_AAM_Practical-Reproducibility-in-Geography-and-Geosciences.pdf 

https://ropensci-archive.github.io/reproducibility-guide/

"Open source: the what and why"
Given the historical context, and given the R package examples later on, you could, depending on the focus, reference work by John Chambers, Robert Gentleman, Ross Ihaka, JJ Allaire, Hadley Wickham and Joe Cheng etc. This could help bridge into the examples later on in the paper.

"How can I see the activity of an open-source project?" 
This jumps into OS projects and more specifically packages. There could be a section about the languages and how they are built and maintained etc., like R core etc. R foundation etc. and how packages extend the capabilities by the community. Might take a look at the appendix here for some ideas:

How do I select an R package for my clinical workflow?
https://www.lexjansen.com/phuse-us/2019/tt/TT11.pdf

"How do I find open-source projects?"
Maybe list Bioconductor and work by ropensci. Could list some examples from the Python sciences packages/ecosystem too.

"In such cases, you may need to extend, or start a new package." 
Maybe define fork/clone.

"What can help me understand the risks around using an open-source project?"
Lots of good info here as well: 

https://www.pharmar.org/white-paper/

This section could also list the Fred Hutch, GSK and Phuse work on: 

https://github.com/phuse-org/valtools

"Licenses: using a project"
Could be worth mentioning that companies can create a curated list of packages based on packages they want for various reasons, like licenses etc.

"When is a good time to open source?"
Caret is a good example from Pfizer:

https://www.r-project.org/conferences/useR-2010/slides/Kuhn.pdf 
"Pfizer’s Statistics leadership for providing the time and support to create R packages"

https://www.nytimes.com/2009/01/07/technology/business-computing/07program.html

Also, Targets by Will Landau at Lilly is a good example:

https://books.ropensci.org/targets/
https://cran.r-project.org/web/packages/targets/LICENSE

"Company Github orgs"
https://github.com/orgs/Merck/repositories

"Collaboration and governance models"
Some good info here:

https://ropensci.org/stat-software-review/ 

"3.8 When do we need contracts?"
Might list an example from Julia, Python or JS etc. Also, lots of interesting examples of collaborative work in the pkpd space in Open Source:

https://nlmixrdevelopment.github.io/nlmixr/articles/xgxr-nlmixr-ggpmx.html
https://github.com/MetrumResearchGroup
https://pharmpy.github.io/latest/index.html
https://github.com/metrumresearchgroup/2021-r-in-pharma

**Comment by epijim** [comment]
thanks Phil - lots of great comments, mapped to changes in https://github.com/phuse-org/E2E-OS-Guidance/commit/89643a9578b4464c479fcc1c25c341921dd8602e
