### ISSUE TITLE
Feedback from Pfizer

### ISSUE THREAD

**Issue by parmsam-pfizer** [phuse-org/E2E-OS-Guidance#6]
Thank you for the invitation to review and provide feedback on the guidance.  Please let me know if you'd like for me to create separate issues and/or submit a PR. 
- Consider adding R-universe link to section on [how to find open source projects](https://phuse-org.github.io/E2E-OS-Guidance/using.html#how-do-i-find-open-source-projects)
- Add mention of [riskmetric](https://github.com/pharmaR/riskmetric) package to section [on understanding risk](https://phuse-org.github.io/E2E-OS-Guidance/using.html#what-can-help-me-understand-the-risks-around-using-an-open-source-project)
- Might mention [oyster]( https://github.com/sonatype-nexus-community/oysteR) package to assess security risk for a package to section [on understanding risk](https://phuse-org.github.io/E2E-OS-Guidance/using.html#what-can-help-me-understand-the-risks-around-using-an-open-source-project).
- Consider mentioning how open source done right ensures reproducibility. Brunos Rodrigues has a pretty good [blog post](https://www.brodrigues.co/blog/2022-11-16-open_source_repro/) along these lines. 
- Consider adding content links to [references page](https://phuse-org.github.io/E2E-OS-Guidance/references.html).
- Across the page on [releasing open source](https://phuse-org.github.io/E2E-OS-Guidance/releasing.html), please ensure the hyperlinks are properly formatted.
- Delete the line that just says contribution models after the last paragraph on [contracts](https://phuse-org.github.io/E2E-OS-Guidance/releasing.html#when-do-we-need-contracts).

**Comment by epijim** [comment]
> Consider adding R-universe link to section on [how to find open source projects](https://phuse-org.github.io/E2E-OS-Guidance/using.html#how-do-i-find-open-source-projects)

https://github.com/phuse-org/E2E-OS-Guidance/commit/6a2564eb96a50c0556d36e3df16c700b155d833f

**Comment by epijim** [comment]
> Add mention of [riskmetric](https://github.com/pharmaR/riskmetric) package to section [on understanding risk](https://phuse-org.github.io/E2E-OS-Guidance/using.html#what-can-help-me-understand-the-risks-around-using-an-open-source-project)

https://github.com/phuse-org/E2E-OS-Guidance/commit/f7f68e1cd41d0e4bfb301ab3c972601ee6f8f271

**Comment by epijim** [comment]
> Might mention [oyster](https://github.com/sonatype-nexus-community/oysteR) package to assess security risk for a package to section [on understanding risk](https://phuse-org.github.io/E2E-OS-Guidance/using.html#what-can-help-me-understand-the-risks-around-using-an-open-source-project).

https://github.com/phuse-org/E2E-OS-Guidance/commit/7df3187e415d48e4337667a3d14a83790eec5074

**Comment by epijim** [comment]
> Consider mentioning how open source done right ensures reproducibility. Brunos Rodrigues has a pretty good [blog post](https://www.brodrigues.co/blog/2022-11-16-open_source_repro/) along these lines.

Added to 'why'

https://github.com/phuse-org/E2E-OS-Guidance/commit/38c01311e1cb36c58030bbf70bbc27c39f7b4677

**Comment by epijim** [comment]
> Across the page on [releasing open source](https://phuse-org.github.io/E2E-OS-Guidance/releasing.html), please ensure the hyperlinks are properly formatted.

https://github.com/phuse-org/E2E-OS-Guidance/commit/758070dc897a93cf512b0b16d3f43174779b91f7

**Comment by epijim** [comment]
> Consider adding content links to [references page](https://phuse-org.github.io/E2E-OS-Guidance/references.html).

https://github.com/phuse-org/E2E-OS-Guidance/commit/eed1a6cb5ada3ac0a73d5dfd0af505b3d198a6fe

**Comment by epijim** [comment]
> Delete the line that just says contribution models after the last paragraph on [contracts](https://phuse-org.github.io/E2E-OS-Guidance/releasing.html#when-do-we-need-contracts).

https://github.com/phuse-org/E2E-OS-Guidance/commit/1052d8927f44a4915817a21fed4643047ee41aef
